---
title: "Bivariate distributions"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Covariance matrix
```{r}
# Standard deviations  
sig_x <- 0.10
sig_y <- 0.05
# correlation
rho_xy <- 0.9

# Covariance between X and Y
sig_xy <- rho_xy * sig_x * sig_y

# Covariance matrix
Sigma_xy <- matrix(c(sig_x ^ 2, sig_xy, sig_xy, sig_y ^ 2), nrow = 2, ncol = 2)

```

## Simulate multivariate data
```{r}

library("mvtnorm")

# Means
mu_x <- 0.05
mu_y <- 0.025

# Simulate 100 observations
set.seed(123)  # for reproducibility
xy_vals <- rmvnorm(100,mean=c(mu_x,mu_y),sigma=Sigma_xy)

# Plot the simulated data
plot(xy_vals,pch=16,cex=1.5,col='blue',main='Bivariate normal: corr = 0.9',xlab='x',ylab='y')
# Add lines
abline(v=mu_x,h=mu_y)
# Add line segments
segments(x0 = 0, y0 = -1e10, x1 = 0, y1 = 0, col = "red")
segments(x0 = -1e10, y0 = 0, x1 = 0, y1 = 0, col = "red")
# The the joint probability Pr(X≤0,Y≤0).
pmvnorm(lower=c(-Inf, -Inf), upper=c(0,0), mean=c(mu_x,mu_y), sigma = Sigma_xy)

```












